### ISSUE TITLE
Latest version fails with 'called `Result::unwrap()` on an `Err` value: Invalid'

### ISSUE THREAD

**Issue by mrmishmash** [mikispag/bitiodine#15]
Built the latest version, machine is Windows, with the latest version of the blockchain:

```
C:\dev\bitiodine\target\release>bitiodine-rust --blocks-dir "G:\BitcoinData\blocks" --output "../../clusters.csv"
2018-12-08 15:24:20.2447 - INFO - Parsing the blockchain: block file 0/1455...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid', libcore\result.rs:1009:5
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/abe02cefd6cd1916df62ad7dc80161bea50b72e8\src/libstd\sys\windows\backtrace\mod.rs:104
   1: std::sys::windows::backtrace::set_frames
             at /rustc/abe02cefd6cd1916df62ad7dc80161bea50b72e8\src/libstd\sys\windows\backtrace\mod.rs:104
   2: std::sys::windows::backtrace::set_frames
             at /rustc/abe02cefd6cd1916df62ad7dc80161bea50b72e8\src/libstd\sys\windows\backtrace\mod.rs:104
   3: std::sys::windows::backtrace::set_frames
             at /rustc/abe02cefd6cd1916df62ad7dc80161bea50b72e8\src/libstd\sys\windows\backtrace\mod.rs:104
   4: std::sys::windows::backtrace::set_frames
             at /rustc/abe02cefd6cd1916df62ad7dc80161bea50b72e8\src/libstd\sys\windows\backtrace\mod.rs:104
   5: std::panicking::default_hook
             at /rustc/abe02cefd6cd1916df62ad7dc80161bea50b72e8\src/libstd\panicking.rs:227
   6: std::panicking::default_hook
             at /rustc/abe02cefd6cd1916df62ad7dc80161bea50b72e8\src/libstd\panicking.rs:227
   7: std::panicking::continue_panic_fmt
             at /rustc/abe02cefd6cd1916df62ad7dc80161bea50b72e8\src/libstd\panicking.rs:390
   8: std::panicking::rust_begin_panic
             at /rustc/abe02cefd6cd1916df62ad7dc80161bea50b72e8\src/libstd\panicking.rs:325
   9: core::panicking::panic_fmt
             at /rustc/abe02cefd6cd1916df62ad7dc80161bea50b72e8\src/libcore\panicking.rs:77
  10: <unknown>
  11: main
  12: <unknown>
  13: main
  14: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:64
  15: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:64
  16: BaseThreadInitThunk
  17: RtlUserThreadStart
```

**Comment by mikispag** [comment]
- Please compile it in debug mode and provide a more meaningful backtrace, possibly with a gdb trace.
- Have you tried putting absolute paths as arguments to the command line executable?

**Comment by mikispag** [comment]
Closing as the project is now unmaintained.
