### ISSUE TITLE
Issue in running 

### ISSUE THREAD

**Issue by souvikhaldar** [mikispag/bitiodine#21]
I'm facing the below issues, kindly suggest a solution:-
```
± ./bitiodine-rust -b /mnt/ssd/bitcoincore/blocks -v 2

thread 'main' panicked at /home/hornet/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.4.16/src/parser/error.rs:32:9:
Mismatch between definition and access of `v`. Could not downcast to TypeId { t: 7428646492878894209665195255548636123 }, need to downcast to TypeId { t: 263171357195085286585474072027052583236 }

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by souvikhaldar** [comment]
Verbose-
```
hornet at x360 in ~/Development/bitiodine/target/release on master
± export RUST_BACKTRACE=1

hornet at x360 in ~/Development/bitiodine/target/release on master
± ./bitiodine-rust -b /mnt/ssd/bitcoincore/blocks -v 2

thread 'main' panicked at /home/hornet/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.4.16/src/parser/error.rs:32:9:
Mismatch between definition and access of `v`. Could not downcast to TypeId { t: 7428646492878894209665195255548636123 }, need to downcast to TypeId { t: 263171357195085286585474072027052583236 }

stack backtrace:
   0: rust_begin_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14                                                                                            2: bitiodine_rust::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```
